# Generated by Django 4.2.3 on 2023-08-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='codegery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('codegery_image', models.ImageField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('prodect_image', models.ImageField(default='', upload_to='')),
                ('more_prodect_image', models.ImageField(default='', upload_to='')),
                ('Uploadet_at', models.DateTimeField(auto_now_add=True)),
                ('Prodect_oner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('codegery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exchenger.codegery')),
            ],
        ),
    ]
