# Generated by Django 4.2.4 on 2023-08-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchenger', '0002_alter_codegery_description_alter_prodect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
